### ISSUE TITLE
Cannot install unsigned extensions in Firefox Release channel. 

### ISSUE THREAD

**Issue by brpaz** [jplattel/obsidian-clipper#21]
Hello.

I tried installing the extension in Firefox, but it seems that the option to allow Unsigned extensions doesn't work in the normal stable channel (only in Nightly and Developer) channels.

So it would be nice, if this extension can be uploaded to the Firefox Add-Ons website.

**Comment by jplattel** [comment]
I've tried submitting the extension for firefox, but it couldn't pass their testing due to the fact it uses the `obsidian://` protocol. I've tried submitting it multiple times with additional information, but it still didn't pass..

I would love to have it for Firefox, but I'm stuck with their testing at the moment. If there are any pointers, feel free to help me out here! Thanks ✌️

**Comment by jplattel** [comment]
A beta is now available on: https://addons.mozilla.org/en-US/firefox/addon/obsidian-clipper/ :)
